version: 2.1

parameters:
  run_integration_tests:
    type: boolean
    default: false

jobs:
  mytestjob:
    machine: true
    steps:
      - run: echo "test"
  dummy:
    machine: true
    steps:
      - run: echo "dummy"
workflows:
  version: 2
  integration_tests:
    when: << pipeline.parameters.run_integration_tests >>
    jobs:
      - mytestjob
  other:
    jobs:
      - dummy
