version: 2.1

parameters:
  run:
    type: boolean
    default: false

jobs:
  mytestjob:
    machine: true
    steps:
      - run: echo "test"
  dummy:
    machine: true
    steps:
      - run: echo "dummy"
workflows:
  version: 2
  other:
    jobs:
      - dummy
  triggered:
    when: << pipeline.parameters.run >>
    jobs:
      - dummy
      - mytestjob:
          requires:
            - dummy
