version: 2.1

parameters:
  run:
    type: boolean
    default: false

jobs:
  mytestjob:
    machine: true
    steps:
      - run: echo "test"
  dummy:
    machine: true
    steps:
      - run: echo "Lots of artifacts!"
  artifact-ios:
    docker:
      - image: python:3.6.3-jessie
    working_directory: /tmp
    steps:
      - run:
          name: Creating ios artifact
          command: |
            sleep 180;
            echo "ios" > Mattermost_Beta.ipa;
      - store_artifacts:
          path: "Mattermost_Beta.ipa"
  artifact-android:
    docker:
      - image: python:3.6.3-jessie
    working_directory: /tmp
    steps:
      - run:
          name: Creating android artifact
          command: |
            echo "android" > Mattermost_Beta.apk;
      - store_artifacts:
          path: "Mattermost_Beta.apk"

workflows:
  version: 2
  other:
    jobs:
      - dummy
  triggered:
    when: << pipeline.parameters.run >>
    jobs:
      - dummy
      - mytestjob:
          requires:
            - dummy
  artifact-test:
    jobs:
      - artifact-ios:
          filters:
            branches:
              only: /^build-pr-.*/
      - artifact-android:
          filters:
            branches:
              only: /^build-pr-.*/
