version: 2.1


jobs:
  dummy:
    machine: true
    steps:
      - run: expr length "${TRIGGER_CIRCLECI_EE_TOKEN}"
      - run: echo ${CIRCLE_BRANCH}
      - run: echo ${CIRCLE_SHA1}
      #      - when:
      #          condition: $CIRCLE_PULL_REQUEST
      #          steps:
      #            - run: expr length "${TRIGGER_CIRCLECI_EE_TOKEN}"
      - run:
          name: Trigger enterprise
          command: |
            curl \
              --request POST \
              --url https://circleci.com/api/v2/project/gh/metanerd/circleci-ee/pipeline \
              --user ${TRIGGER_CIRCLECI_EE_TOKEN} \
              --header 'content-type: application/json' \
              --data '{"parameters": {"external_branch": $CIRCLE_BRANCH, "external_sha": $CIRCLE_SHA1}}'

workflows:
  version: 2
  other:
    jobs:
      - dummy:
          context: metanerd-trigger-ee
