### totally not different from master
version: 2

jobs:
  job_to_trigger:
    machine: true
    steps:
      - run:
          command: |
            if [[ ${IS_BUILD_APPS_FOR_PR_LABEL} ]]; then
              echo "${CIRCLE_BUILD_URL} and ${CIRCLE_SHA1}"
            fi
  job_regular:
    machine: true
    steps:
      - run: echo "No Label"

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - job_to_trigger
      - job_regular
