version: 2.1

parameters:
  run:
    type: boolean
    default: false

jobs:
  mytestjob:
    machine: true
    steps:
      - run: echo "test"
  dummy:
    machine: true
    steps:
      - run: echo "Lots of artifacts!"
  artifact-fast:
    docker:
      - image: python:3.6.3-jessie
    working_directory: /tmp
    steps:
      - run:
          name: Creating fast artifact
          command: |
            mkdir /tmp/artifacts;
            echo "my artifact files in a dir" > /tmp/artifacts/artifact-2;
      - store_artifacts:
          path: /tmp/artifacts

  artifact-slow:
    docker:
      - image: python:3.6.3-jessie
    working_directory: /tmp
    steps:
      - run:
         name: Creating slow artifact
         command: |
           sleep 180;
           mkdir /tmp/artifacts;
           echo "my artifact files in a dir" > /tmp/artifacts/artifact-3;
      - store_artifacts:
          path: /tmp/artifacts
workflows:
  version: 2
  other:
    jobs:
      - dummy
  triggered:
    when: << pipeline.parameters.run >>
    jobs:
      - dummy
      - mytestjob:
          requires:
            - dummy
  artifact-test:
    jobs:
      - artifact-fast:
          filters:
            branches:
              only: /^build-pr-.*/
      - artifact-slow:
          filters:
            branches:
              only: /^build-pr-.*/
