version: 2.1

parameters:
  run:
    type: boolean
    default: false

jobs:
  test:
    machine: true
    steps:
      - run: echo "hi"
  artifact-ios:
    docker:
      - image: python:3.6.3-jessie
    working_directory: /tmp
    steps:
      - run:
          name: Creating ios artifact
          command: |
            sleep 180;
            echo "ios" > Mattermost_Beta1.ipa;
      - store_artifacts:
          path: "Mattermost_Beta.ipa"
  artifact-android:
    docker:
      - image: python:3.6.3-jessie
    working_directory: /tmp
    steps:
      - run:
          name: Creating android artifact
          command: |
            echo "android" > Mattermost_Beta.apk;
      - store_artifacts:
          path: "Mattermost_Beta2.apk"

workflows:
  version: 2
  artifact-test:
    jobs:
      - test
      - artifact-ios:
          requires:
            - test
          filters:
            branches:
              only: /^build-pr-.*/
      - artifact-android:
          requires:
            - test
          filters:
            branches:
              only: /^build-pr-.*/
