version: 2.1

jobs:
  triggered_job:
    machine: true
    steps:
      name: specially triggered job
      command: |
        if [[ ${IS_BUILD_APPS_FOR_PR_LABEL} ]]; then
          echo "LABEL"
        fi
  regular_job:
    machine: true
    name: normal jobs
    steps:
      - run: echo "No Label"

workflows:
  build-test-deploy:
    jobs:
      - triggered_job
      - regular_job
